import type {
  BuiltInSkillDefinition,
  BuiltInSkillId,
  SkillPackDefinition,
} from "@shared/domain";

const builtInSkills: BuiltInSkillDefinition[] = [
  {
    id: "project_brief",
    version: "1.0.0",
    name: "项目速记卡",
    description: "基于项目资料生成答辩速记卡。",
    trigger: { mode: "workspace", event: "page_load" },
    output: { type: "project_brief" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveProjectContext"],
    packIds: ["core-training"],
    fallbackPolicy: "required",
    traceTags: ["brief"],
    inputSchemaName: "ProjectBriefInput",
    outputSchemaName: "ProjectBriefOutput",
  },
  {
    id: "slide_script",
    version: "1.0.0",
    name: "逐页讲稿",
    description: "基于当前页资料生成讲稿、30 秒版和关键词版。",
    trigger: { mode: "workspace", event: "page_load" },
    output: { type: "slide_script" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["core-training"],
    fallbackPolicy: "required",
    traceTags: ["brief"],
    inputSchemaName: "SlideScriptInput",
    outputSchemaName: "SlideScriptOutput",
  },
  {
    id: "risk_questions",
    version: "1.0.0",
    name: "高危追问",
    description: "提炼老师最可能追问的高风险问题。",
    trigger: { mode: "workspace", event: "page_load" },
    output: { type: "risk_questions" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveRiskQuestions"],
    packIds: ["core-training", "deep-dive"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "RiskQuestionsInput",
    outputSchemaName: "RiskQuestionsOutput",
  },
  {
    id: "current_slide_followup",
    version: "1.0.0",
    name: "当前页追问",
    description: "围绕当前 PPT 页持续追问并给出提示。",
    trigger: { mode: "defense", event: "user_finished_slide" },
    output: { type: "teacher_followup" },
    projectTypes: ["software_ai_data", "course_presentation", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["core-training", "defense-advanced"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "DefenseTurnInput",
    outputSchemaName: "DefenseTurnOutput",
  },
  {
    id: "code_explainer",
    version: "1.0.0",
    name: "代码解释",
    description: "基于代码上下文解释当前实现、调用链和关键边界。",
    trigger: { mode: "file_explanation", event: "code_explain" },
    output: { type: "code_explainer" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveCodeContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["code_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
  {
    id: "data_survey_explainer",
    version: "1.0.0",
    name: "数据说明",
    description: "围绕数据集、字段、指标和数据边界做解释。",
    trigger: { mode: "file_explanation", event: "dataset_explain" },
    output: { type: "data_survey_explainer" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveFileContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["dataset_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
  {
    id: "weakness_deep_dive",
    version: "1.0.0",
    name: "薄弱点钻研",
    description: "把答不上来的问题转成证据链和学习清单。",
    trigger: { mode: "deep_dive", event: "request_followup" },
    output: { type: "deep_dive" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveKnowledgeNodeContext", "createDeepDive"],
    packIds: ["deep-dive"],
    fallbackPolicy: "required",
    traceTags: ["deep_dive"],
    inputSchemaName: "WeaknessDeepDiveInput",
    outputSchemaName: "WeaknessDeepDiveOutput",
  },
  {
    id: "fallback_answer",
    version: "1.0.0",
    name: "统一兜底回答",
    description: "当资料不足或主技能失败时，返回受控兜底话术。",
    trigger: { mode: "workspace", event: "fallback" },
    output: { type: "fallback_answer" },
    projectTypes: ["software_ai_data", "course_presentation", "competition_pitch", "general"],
    allowedTools: ["retrieveProjectContext"],
    packIds: ["core-training", "deep-dive", "defense-advanced", "file-explainers"],
    fallbackPolicy: "none",
    traceTags: ["brief", "defense", "file_explanation"],
    inputSchemaName: "FallbackAnswerInput",
    outputSchemaName: "FallbackAnswerOutput",
  },
  {
    id: "review_report",
    version: "1.0.0",
    name: "复盘报告",
    description: "结束训练后提炼薄弱点、得分和下一轮建议。",
    trigger: { mode: "review", event: "review_generate" },
    output: { type: "review_report" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["writeReview", "createWeakness", "createDeepDive"],
    packIds: ["core-training", "deep-dive"],
    fallbackPolicy: "required",
    traceTags: ["review"],
    inputSchemaName: "ReviewReportInput",
    outputSchemaName: "ReviewReportOutput",
  },
  {
    id: "content_repurpose",
    version: "1.0.0",
    name: "内容二次创作",
    description: "把训练结果转成 QQ 空间摘要和视频口播稿。",
    trigger: { mode: "export", event: "content_export" },
    output: { type: "content_export" },
    projectTypes: ["software_ai_data", "competition_pitch", "general"],
    allowedTools: ["writeContentExport"],
    packIds: ["deep-dive"],
    fallbackPolicy: "required",
    traceTags: ["content_export"],
    inputSchemaName: "ContentRepurposeInput",
    outputSchemaName: "ContentRepurposeOutput",
  },
  {
    id: "teacher_style_followup",
    version: "1.0.0",
    name: "老师风格追问",
    description: "基于严格老师风格追加一轮更尖锐的追问。",
    trigger: { mode: "defense", event: "teacher_style_followup" },
    output: { type: "teacher_followup" },
    projectTypes: ["software_ai_data", "course_presentation", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["defense-advanced"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "DefenseTurnInput",
    outputSchemaName: "DefenseTurnOutput",
  },
  {
    id: "rubric_scoring",
    version: "1.0.0",
    name: "评分量表",
    description: "按表达、证据和抗压度输出结构化评分。",
    trigger: { mode: "defense", event: "rubric_score" },
    output: { type: "rubric_scoring" },
    projectTypes: ["software_ai_data", "course_presentation", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["defense-advanced"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "RubricScoringInput",
    outputSchemaName: "RubricScoringOutput",
  },
  {
    id: "member_scope_defense",
    version: "1.0.0",
    name: "个人负责范围答辩",
    description: "检查个人负责范围是否说清楚，并给出补答。",
    trigger: { mode: "defense", event: "member_scope_check" },
    output: { type: "member_scope_defense" },
    projectTypes: ["software_ai_data", "course_presentation", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["defense-advanced"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "MemberScopeDefenseInput",
    outputSchemaName: "MemberScopeDefenseOutput",
  },
  {
    id: "evidence_gap_check",
    version: "1.0.0",
    name: "证据缺口检查",
    description: "检查回答里有哪些结论缺少资料或代码证据。",
    trigger: { mode: "defense", event: "evidence_gap_check" },
    output: { type: "evidence_gap_check" },
    projectTypes: ["software_ai_data", "course_presentation", "general"],
    allowedTools: ["retrieveSlideContext"],
    packIds: ["defense-advanced"],
    fallbackPolicy: "required",
    traceTags: ["defense"],
    inputSchemaName: "EvidenceGapCheckInput",
    outputSchemaName: "EvidenceGapCheckOutput",
  },
  {
    id: "file_outline_explainer",
    version: "1.0.0",
    name: "文件大纲讲解",
    description: "输出资料大纲、重点和追问建议。",
    trigger: { mode: "file_explanation", event: "file_outline" },
    output: { type: "file_outline_explainer" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveFileContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["file_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
  {
    id: "architecture_explainer",
    version: "1.0.0",
    name: "架构讲解",
    description: "围绕系统架构、模块关系和数据流给出解释。",
    trigger: { mode: "knowledge_node", event: "architecture_explain" },
    output: { type: "architecture_explainer" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveKnowledgeNodeContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["file_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
  {
    id: "dataset_explainer",
    version: "1.0.0",
    name: "数据集讲解",
    description: "围绕数据字段、指标、口径和异常点讲解。",
    trigger: { mode: "file_explanation", event: "dataset_overview" },
    output: { type: "dataset_explainer" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveFileContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["dataset_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
  {
    id: "code_walkthrough",
    version: "1.0.0",
    name: "代码走查",
    description: "按文件路径和逻辑顺序解释关键实现步骤。",
    trigger: { mode: "file_explanation", event: "code_walkthrough" },
    output: { type: "code_walkthrough" },
    projectTypes: ["software_ai_data", "general"],
    allowedTools: ["retrieveCodeContext"],
    packIds: ["file-explainers"],
    fallbackPolicy: "required",
    traceTags: ["code_explanation"],
    inputSchemaName: "ExplanationInput",
    outputSchemaName: "ExplanationOutput",
  },
];

const skillPacks: SkillPackDefinition[] = [
  {
    id: "core-training",
    name: "Core Training",
    description: "项目速记、逐页讲稿、当前页追问和复盘报告。",
    scope: "system",
    skills: ["project_brief", "slide_script", "risk_questions", "current_slide_followup", "review_report"],
    defaultEnabled: true,
    recommendedFor: ["workspace", "defense", "review"],
  },
  {
    id: "deep-dive",
    name: "Deep Dive",
    description: "薄弱点钻研、内容导出和统一兜底。",
    scope: "system",
    skills: ["weakness_deep_dive", "content_repurpose", "fallback_answer"],
    defaultEnabled: true,
    recommendedFor: ["review", "deep_dive"],
  },
  {
    id: "defense-advanced",
    name: "Defense Advanced",
    description: "老师风格追问、评分量表、证据缺口和个人负责范围检查。",
    scope: "system",
    skills: ["teacher_style_followup", "rubric_scoring", "member_scope_defense", "evidence_gap_check"],
    defaultEnabled: true,
    recommendedFor: ["defense", "review"],
  },
  {
    id: "file-explainers",
    name: "File Explainers",
    description: "文件大纲、架构、数据集和代码走查说明类技能。",
    scope: "system",
    skills: [
      "code_explainer",
      "data_survey_explainer",
      "file_outline_explainer",
      "architecture_explainer",
      "dataset_explainer",
      "code_walkthrough",
    ],
    defaultEnabled: true,
    recommendedFor: ["file_explanation", "workspace"],
  },
];

export function listBuiltInSkills() {
  return [...builtInSkills];
}

export function getBuiltInSkill(skillId: BuiltInSkillId) {
  return builtInSkills.find((skill) => skill.id === skillId) ?? null;
}

export function hasBuiltInSkill(skillId: string): skillId is BuiltInSkillId {
  return builtInSkills.some((skill) => skill.id === skillId);
}

export function listBuiltInSkillPacks() {
  return [...skillPacks];
}

export function getBuiltInSkillPack(packId: SkillPackDefinition["id"]) {
  return skillPacks.find((pack) => pack.id === packId) ?? null;
}

export function listSkillsForPack(packId: SkillPackDefinition["id"]) {
  return builtInSkills.filter((skill) => skill.packIds.includes(packId));
}
