ALTER TABLE "TrainingSession"
ADD COLUMN IF NOT EXISTS "hintCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "followUpCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "detectedWeaknesses" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "lastRetrievedSources" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "shouldFinish" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "TrainingTurn"
ADD COLUMN IF NOT EXISTS "slideIndex" INTEGER,
ADD COLUMN IF NOT EXISTS "slideTitle" TEXT,
ADD COLUMN IF NOT EXISTS "retrievedSourceIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "speech" JSONB NOT NULL DEFAULT 'null'::jsonb;

ALTER TABLE "ReviewReport"
ADD COLUMN IF NOT EXISTS "clarityScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "evidenceScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "pressureScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "betterAnswers" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "recommendedSkills" JSONB NOT NULL DEFAULT '[]'::jsonb;
