ALTER TABLE "TrainingSession"
ADD COLUMN IF NOT EXISTS "currentPhase" TEXT NOT NULL DEFAULT 'idle',
ADD COLUMN IF NOT EXISTS "currentSlideIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "completedSlideIds" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "currentFollowupCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "finalQuestionIndex" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastPhaseAt" TIMESTAMP(3) NOT NULL DEFAULT now();

ALTER TABLE "RealtimeSession"
ADD COLUMN IF NOT EXISTS "currentPhase" TEXT NOT NULL DEFAULT 'idle',
ADD COLUMN IF NOT EXISTS "currentSlideIndex" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "TrainingTurn"
ADD COLUMN IF NOT EXISTS "turnType" TEXT,
ADD COLUMN IF NOT EXISTS "phaseBefore" TEXT,
ADD COLUMN IF NOT EXISTS "phaseAfter" TEXT,
ADD COLUMN IF NOT EXISTS "slideFeedbackSummary" TEXT;
